### ISSUE TITLE
Project Outline: Feedback

### ISSUE THREAD

**Issue by lindskelsey** [richardziegler/liftoff-assignments#1]
The scope of this project is reasonable for the length of the class. Your biggest challenge will be learning Vue, how to write an API, and how to consume that API in Vue. I would suggest starting with the submission/voting features as your MVP, and adding the login and permissions features later. Those initial features will be a little more straight-forward, and I'd expect after building them you will feel comfortable enough with the new technologies to tackle the more complex features.

**Comment by richardziegler** [comment]
Thanks Lindsay! I'll start working on the more foundational features and build in the other once those are solid.
